--PART B3
--TODO 1: Adding Keys
--Every record in the  ‘vote’ table should be uniquely identified using the columns ‘voter_id’

ALTER TABLE vote ADD PRIMARY KEY(voter_id);


ALTER TABLE CONSTITUENCY ADD VOTER_ID CHAR(10)

ALTER TABLE CONSTITUENCY
ADD FOREIGN KEY (VOTER_ID) REFERENCES VOTE(VOTER_ID);  


ALTER TABLE VOTE
ADD FOREIGN KEY (VOTER_ID) REFERENCES VOTER(VOTER_ID);




ALTER TABLE VOTER MODIFY VOTER_ID CHAR(10) PRIMARY KEY; 



ALTER TABLE CONSTITUENCY MODIFY CONSTITUENCY_ID char(10) PRIMARY KEY;


